name: Deploy to GAE
on:
  push:
    branches:
      - 'release'
      - 'develop'
      - 'master'
  pull_request:
    branches:
      - 'release'
jobs:
  auto_deploy_gae:
    permissions: write-all
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: yarn install
        run: yarn install
      - name: yarn build
        run: yarn build
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: Get branch name
        id: get_branch
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/})"
      - name: Print branch name
        run: echo ${{ steps.get_branch.outputs.branch }}
      - name: 'Deploy to App Engine'
        id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v0'
        with:
          deliverables: 'app.yaml'
          promote: ${{ steps.get_branch.outputs.branch =='release' }}
          version: ${{ steps.get_branch.outputs.branch }}
      - name: 'update repo detail website'
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        run: |
          gh repo edit -h ${{steps.deploy.outputs.url}}